### PR TITLE
Update scala 2.13.0-RC2 to 2.13.0-RC3

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by 2m** [comment]
Validation failed because of the missing specs2 release for 2.13.0-RC3. That is being worked on currently and here is a ticket to track that: https://github.com/etorreborre/specs2/issues/743

**Comment by raboof** [comment]
published to staging at https://oss.sonatype.org/content/groups/staging/io/spray/spray-json_2.13.0-RC3/1.3.5/ - will release after testing

**Comment by Philippus** [comment]
specs2 is now available for 2.13.0-RC3, so a rebuild should do the trick.

**Comment by raboof** [comment]
triggered

**Comment by godenji** [comment]
and now `specs2` is available for 2.13.0, let's follow suit here...

**Pull request merged**
