### PR TITLE
Replace ClassManifest to ClassTag

### PR DESCRIPTION
**Pull request by magnolia-k**
ClassManifest has been deprecated as of 2.10 and replaced with ClassTag
because a warning message is displayed at compile time.

### CODE REVIEW

**Comment by ktoso** [comment]
This would break binary compatibility so we need to bump a major version to accept this I think.

cc @sirthias @jrudolph

**Comment by zhaocon** [comment]
This is a duplication of my PR https://github.com/spray/spray-json/pull/216...

**Comment by ktoso** [comment]
Same comment applies there though. I don't think we can just merge either of these.

Unless you see a way to do it?

**Comment by ktoso** [comment]
Refs #215

**Comment by magnolia-k** [comment]
Sorry to have issued duplicate PR.

The warning related to 'Unit' has already been solved with another PR, and exactly the same contents except that part. It does not matter which one you apply.

**Comment by jrudolph** [comment]
I figured that the binary compat argument doesn't hold because `ClassManifest` is just a type alias to `ClassTag`, everything should continue to work after this change (as now verified by travis as well). I added a slight cosmetic change but I think it's now ready to go.

**Comment by jrudolph** [comment]
Thanks, @magnolia-k and @zhaocon.

**Pull request merged**
