### PR TITLE
Update scala 2.13.0-RC3 to 2.13.0

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by raboof** [comment]
Publishing `v1.3.5-2.13.0` to Maven Central as 1.3.5 for Scala 2.13.0

**Comment by raboof** [comment]
refs #300

**Comment by raboof** [comment]
Travis failure is unrelated but not interemittent: we have to update the travis configuration to get the JDK from Jabba instead of using the one (no longer) shipping with Travis

**Comment by Philippus** [comment]
we could also switch to openjdk or set `dist: trusty` and still use oraclejdk8 as is for a while

**Pull request merged**
