### PR TITLE
Correct Example In Providing JsonFormats for other Types

### PR DESCRIPTION
**Pull request by shankarshastri**
Correct Example In Providing JsonFormats for other Types.
@sirthias @jrudolph @ktoso

### CODE REVIEW

**Comment by ktoso** [comment]
It is on purpose not a case class to show how to deal with not-case-class es

**Comment by ktoso** [comment]
As it states just above there: `Of course you can also supply (de)serialization logic for types that aren't case classes.`

**Comment by ktoso** [comment]
Thanks for the PR but the change is not an improvement, sorry

**Comment by shankarshastri** [comment]
@ktoso , But then this should be 
val json = Color("CadetBlue", 95, 158, 160).toJson => val json = new Color("CadetBlue", 95, 158, 160).toJson
?

**Comment by ktoso** [comment]
Ah yes :) Please change that line instead :) thanks!

**Comment by shankarshastri** [comment]
Done @ktoso. Thanks 😄

**Comment by ktoso** [comment]
Thanks!

**Comment by shankarshastri** [comment]
@ktoso, I was going through the repo actually found that ReadmeSpec.scala. This file also needs to be updated right with non-case-class tests?

**Pull request merged**
